#!/bin/bash

realpath () {
(
  TARGET_FILE="$1"
  CHECK_CYGWIN="$2"

  cd "$(dirname "$TARGET_FILE")"
  TARGET_FILE=$(basename "$TARGET_FILE")

  COUNT=0
  while [ -L "$TARGET_FILE" -a $COUNT -lt 100 ]
  do
      TARGET_FILE=$(readlink "$TARGET_FILE")
      cd "$(dirname "$TARGET_FILE")"
      TARGET_FILE=$(basename "$TARGET_FILE")
      COUNT=$(($COUNT + 1))
  done

  if [ "$TARGET_FILE" == "." -o "$TARGET_FILE" == ".." ]; then
    cd "$TARGET_FILE"
    TARGET_FILEPATH=
  else
    TARGET_FILEPATH=/$TARGET_FILE
  fi

  # make sure we grab the actual windows path, instead of cygwin's path.
  if [[ "x$CHECK_CYGWIN" == "x" ]]; then
    echo "$(pwd -P)/$TARGET_FILE"
  else
    echo $(cygwinpath "$(pwd -P)/$TARGET_FILE")
  fi
)
}

declare -r real_script_path="$(realpath "$0")"
declare -r app_home="$(realpath "$(dirname "$real_script_path")")"
declare -r lib_dir="$(realpath "${app_home}/../lib")"
declare -r conf_dir="$(realpath "${app_home}/../conf")"
declare -a app_mainclass=(${{app_mainclass}})
${{template_declares}}

export SPARK_HOME=/path/to/your/spark/installation
$SPARK_HOME/bin/spark-submit \
--conf "spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$conf_dir/log4j.properties" \
--driver-java-options "-Dconfig.file=$conf_dir/application.conf" \
--properties-file $conf_dir/spark.properties \
--class $app_mainclass \
$app_classpath \
$@
